// <auto-generated />
using System;
using JoaoCarlosRezendeJunior.API.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JoaoCarlosRezendeJunior.API.Migrations
{
    [DbContext(typeof(PedidoContext))]
    [Migration("20181120225558_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JoaoCarlosRezendeJunior.API.Model.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodCliente");

                    b.Property<DateTime>("DataEntrega");

                    b.Property<string>("NomeMedicamento");

                    b.Property<int>("QtdeMedicamento");

                    b.HasKey("IdPedido");

                    b.ToTable("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
